# Generated by Django 2.1.5 on 2019-01-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20190114_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='open_status',
            field=models.CharField(default='open', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='colour',
            field=models.CharField(default='white', max_length=128),
        ),
    ]
